### ISSUE TITLE
Error when switching PostgreSQL version

### ISSUE THREAD

**Issue by sergio-fry** [sergio-fry/devup#16]
Reproduce:

```yaml
version: '3'

services:
  postgres:
    image: postgres:10
    ports:
      - "5432"
```

    devup

```yaml
version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - "5432"
```

Maybe?
--renew-anon-volumes
